environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
    CONFIG: Release

init:
  # line endings magic
  - git config --global core.autocrlf input

before_build:
  # remove some noisy warnings from Xamarin
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - mkdir windowsbuild
  - ps: cd windowsbuild 
  - svn co http://visit.ilight.com/svn/visit/trunk/windowsbuild/MSVC2013-x64/
  - ps: cd .. 
  - svn co http://visit.ilight.com/svn/visit/trunk/src/
  # configure
  - echo Running cmake ...
  - cmake -Hsrc -Bbuild -G "%CMAKE_GENERATOR%" 

build_script:
  #build
  - echo Building ...
  - cmake --build build --config %CONFIG%
